import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import Footer from './components/footer'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [toggleMenu, setToggleMenu] = useState(false)
  const [screenWidth, setScreenWidth] = useState(0);

  const  toggleNav = () => {
    setToggleMenu(!toggleMenu)
  }

  useEffect(() => {
    const changeWidth = () => {
      setScreenWidth(window.innerWidth)
    }
    if (typeof window !== 'undefined') {
      setScreenWidth(window.innerWidth);
      window.addEventListener('resize', changeWidth);
    }

    return () => {
      if (typeof window !== 'undefined') {
        window.removeEventListener('resize', changeWidth);
      }
    };
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Navbar/>

     <div  className={`${styles.heroimg} py-5 mx-auto text-center`}>
      <div className={styles.herotext}>
      <h6 className={styles.heroheader}>We Provide Best IT Solution</h6>
      <p>Alpha Technologies Brings the Power of Data science and artificail Intelligence to Every Business.</p>
      <div>
        <button className='btn btn-secondary'>Our Services</button>
      </div>
      </div>
     </div>
     <div className='d-flex justify-content-center text-center my-5'>
      <div>
      <h4>Our Services</h4>
      <h6>Providing Solutions for Startup and Enterprises</h6>
      </div>
      </div>
      <div className='mx-auto d-flex justify-content-center'>
      <div className={styles.boxcontainer}>
        <div className={styles.box}>
            <div className={styles.globe}>
            <Image src='/globe.png' alt='globe' width={100} height={100} />
            </div>
            <div>
            <h6 className={styles.boxheader}>Managed IT Services</h6>
            <p>Alpha Technologies Brings the power of data science and artificial intelligence to every business.</p>
            </div>
        </div>
        <div className={styles.box}>
            <div className={styles.globe}>
            <Image src='/bell.png' alt='globe' width={100} height={100} />
            </div>
            <div>
            <h6 className={styles.boxheader}>Backup and Recovery</h6>
            <p>Alpha Technologies Brings the power of data science and artificial intelligence to every business.</p>
            </div>
        </div>
        <div className={styles.box}>
            <div className={styles.globe}>
            <Image src='/lock.png' alt='globe' width={100} height={100} />
            </div>
            <div>
            <h6 className={styles.boxheader}>Cyber Security</h6>
            <p>Alpha Technologies Brings the power of data science and artificial intelligence to every business.</p>
            </div>
        </div>
     
     </div>
     </div>
     <div>
      <div className='d-flex justify-content-center text-center my-5'>
        <div>        
        <h3>Services We Offer</h3>
        <p>We offer a wide range of services that best suites our customers Base at Alphaden Technologies</p>
        </div>
      </div>
      </div>
      <div className={styles.servicescontainer}>
        <div className={styles.servicebox}>
          <div>
          <Image src='/support.jpg' alt='globe' width={400} height={250} />
          <div>
            <h6>Chat Support</h6>
          </div>
          </div>
          <div>
            <p>Let your users get in touch with delivery executive for any kind of queries related to their pickup and delivery orders</p>
          </div>
        </div>
        <div className={styles.servicebox}>
          <div>
          <Image src='/sos.jpg' alt='globe' width={400} height={250} />
          <div>
            <h6>SOS Feature</h6>
          </div>
          </div>
          <div>
            <p>Let your users get in touch with delivery executive for any kind of queries related to their pickup and delivery orders</p>
          </div>
        </div>
       
        <div className={styles.servicebox}>
          <div>
          <Image src='/pickup.jpg' alt='globe' width={400} height={250} />
          <div>
            <h6>Pickup Flow</h6>
          </div>
          </div>
          <div>
            <p>Let your users get in touch with delivery executive for any kind of queries related to their pickup and delivery orders</p>
          </div>
        </div>
        <div className={styles.servicebox}>
          <div>
          <Image src='/tracking.jpg' alt='globe' width={400} height={250} />
          <div>
            <h6>Status Update</h6>
          </div>
          </div>
          <div>
            <p>Let your users get in touch with delivery executive for any kind of queries related to their pickup and delivery orders</p>
          </div>
        </div>
        <div className={styles.servicebox}>
          <div>
          <Image src='/promo.jpg' alt='globe' width={400} height={250} />
          <div>
            <h6>Promotions</h6>
          </div>
          </div>
          <div>
            <p>Let your users get in touch with delivery executive for any kind of queries related to their pickup and delivery orders</p>
          </div>
        </div>
        <div className={styles.servicebox}>
          <div>
          <Image src='/refer.jpg' alt='globe' width={400} height={250} />
          <div>
            <h6>Refer a Friend</h6>
          </div>
          </div>
          <div>
            <p>Let your users get in touch with delivery executive for any kind of queries related to their pickup and delivery orders</p>
          </div>
        </div>
      </div>

      <div className={`row ${styles.bgstretch}`}>
        <div className={`col-8 d-flex justify-content-center align-items-center text-center ${styles.innerbg}`}>
          <div>
          <h3>Who we are</h3>
          <p>Alphaden Technologies is a platform that would address the problem of unequal access to fashion brands for Africans by providing a more efficient and equitable distribution channel that enables Africans to discover and purchase items from both African and International fashion brands, creating a win-win situation for all stakeholders involved. To lead the next generation of fashion commerce and engineer the future of fashion, focusing on Africa's contribution to the fashion industry globally.Pashione envisions to be the world's best destination to discover African Fashion brands.</p>
          </div>
        </div>
      </div>

      <div className={`row ${styles.contactus}`}>
        <div className='d-flex justify-content-center my-5'>
          <div>
          <p>Have an Enquiry?</p>
          <h3>Contact Us</h3>
          </div>
         
        </div>
        <div className={`col-12 col-lg-6 d-flex justify-content-center align-items-center ${styles.rightaddress}`}>
          <div>
          <div>
            <p>Address:</p>
            <h5>184 Main Collins Street, Toronto</h5>
          </div>
          <div>
            <p>Phone:</p>
            <h5>(226) 446 9371</h5>
          </div>
          <div>
            <p>Email:</p>
            <h5>confer@gmail.com</h5>
          </div>
          <div>
            <p>Website:</p>
            <h5>www.alphadentechnologies.com</h5>
          </div>
          </div>
        </div>
        <div className={`col-12 col-lg-6  px-5`}>
          <form className={styles.contactform}>
            <div className='d-flex justify-content-between'>
            <input className='form-control mx-2 my-3' name='firstName' placeholder='First Name'/>
            <input className='form-control mx-2 my-3' name='lastName' placeholder='Last Name'/>
            </div>
            <div className='d-flex justify-content-between'>
            <input className='form-control mx-2 my-3' name='email' placeholder='Email Address'/>
            <input className='form-control mx-2 my-3' name='phoneNumber' placeholder='Phone Number'/>
            </div>
            <div>
              <textarea className='form-control mx-2' name='message' placeholder='Your Message'/>
            </div>
            <div className='mx-2 my-3'>
              <button className='btn btn-secondary'>Send Message</button>
            </div>
          </form>
        </div>

      </div>
    
     {/* FOOTER */}
     <Footer/>
    </>
  )
}
